### ISSUE TITLE
Create Home component

### ISSUE THREAD

**Issue by timkeresey** [stacyp2006/RancidTomatillos#1]
- Elements based off of wire frame design
  - header
 - App title
- main section with cards representing movies.
- functional component, direct child of App

**Comment by Geeky-star** [comment]
Can I contribute to this project?
Does it requires only design or any functionality?

**Comment by stacyp2006** [comment]
> Can I contribute to this project?
> Does it requires only design or any functionality?

Sorry, but no. This is school project, so only my partner and I are allowed to contribute.

**Comment by Geeky-star** [comment]
> > Can I contribute to this project?
> > Does it requires only design or any functionality?
> 
> Sorry, but no. This is school project, so only my partner and I are allowed to contribute.

Okay.
